import {
  ACTIVE_STATUS,
  Direction,
  DISPLAY_TYPE,
  EquipmentType,
  FoundationType,
  INPUT_TYPE,
  PropertyName,
  SteelSupport,
  StructureFormSchema,
  StructureType,
} from '../types';

export const STRUCTURE_FORM_SCHEMA: StructureFormSchema = {
  info: [
    {
      name: 'root',
      displayType: DISPLAY_TYPE.ROOT,
      sectionName: PropertyName.STRUCTURE_INFO,
      children: [
        {
          name: 'structure_name',
          label: 'Structure Name',
          excelLabel: 'Structure Name',
          inputType: INPUT_TYPE.TEXT,
          possibleValues: [],
          max: null,
          min: null,
          default: 'TBC',
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.STRUCTURE_INFO,
        },
        {
          name: 'structure_location',
          label: 'Structure Location',
          excelLabel: 'Structure Location',
          inputType: INPUT_TYPE.TEXT,
          possibleValues: [],
          max: null,
          min: null,
          default: 'TBC',
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.STRUCTURE_INFO,
        },
        {
          name: 'structure_type',
          label: 'Structure Type',
          excelLabel: 'Structure Type',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: Object.values(StructureType),
          max: null,
          min: null,
          default: StructureType.CANTILEVER,
          hintText: 'For SSA use Cantilever',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.STRUCTURE_INFO,
        },
        // {
        //   name: 'additional_load_factor',
        //   label: 'Passive Provision',
        //  excelLabel:bel: 'Passive Provision',
        //   inputType: INPUT_TYPE.NUMBER,
        //   possibleValues: [],
        //   max: 10000,
        //   min: -10000,
        //   default: 0,
        //   hintText:
        //       'Percentage increase for all loads applied to the structure for passive provision',
        //   unit: '%',
        //   displayType: DISPLAY_TYPE.INPUT,
        //   groupName: 'root',
        //   sectionName: PropertyName.STRUCTURE_INFO,
        // },
      ],
    },
  ],
  basics: [
    {
      name: 'mast_a',
      label: 'Mast A',
      excelLabel: 'Mast A',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.STRUCTURE_BASIC,
      children: [
        {
          name: 'steelwork',
          label: 'Steelwork',
          excelLabel: 'Steelwork',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: [],
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [
                  'UC152X152X23',
                  'UC152X152X30',
                  'UC203X203X46',
                  'UC254X254X73',
                  'UC308X305X97',
                  'UC356X368X129',
                  'UC356X368X177',
                  'UC356X368X202',
                  'DC300X90X41',
                ],
              },
              {
                case: StructureType.TTC,
                resolve: [
                  'DC380X100X54',
                ],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  'DC300X90X41',
                ],
              },
            ],
          },
          max: null,
          min: null,
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.PORTAL,
                resolve: 'DC300X90X41',
              },
              {
                case: StructureType.CANTILEVER,
                resolve: 'UC254X254X73',
              },
              {
                case: StructureType.TTC,
                resolve: 'DC380X100X54',
              },
            ],
          },
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_a',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'foundation_level',
          label: 'Foundation Level',
          excelLabel: 'Foundation Level',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: -10,
          default: 0,
          hintText: 'Measured from high rail to top of foundation level',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_a',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'length',
          label: 'Length',
          excelLabel: 'Length',
          inputType: INPUT_TYPE.NUMBER,
          activeCriteria: {
            pathToCheck: [PropertyName.STRUCTURE_BASIC, 'mast_a', 'steelwork'],
            allowedValues: [
              'UC152X152X23',
              'UC152X152X30',
              'UC203X203X46',
              'UC254X254X73',
              'UC308X305X97',
              'UC356X368X129',
              'UC356X368X177',
              'UC356X368X202',
            ],
          },
          activeStatus: ACTIVE_STATUS.ACTIVE,
          max: 20,
          min: 1,
          default: 7,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_a',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'length',
          label: 'Length',
          excelLabel: 'Length',
          inputType: INPUT_TYPE.DROPDOWN,
          activeCriteria: {
            pathToCheck: [PropertyName.STRUCTURE_BASIC, 'mast_a', 'steelwork'],
            allowedValues: [
              'DC300X90X41',
            ],
          },
          activeStatus: ACTIVE_STATUS.ACTIVE,
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [
                  4, 4.2, 4.4, 4.6, 4.8, 5, 5.2, 5.4,
                  5.6, 5.8, 6, 6.2, 6.4, 6.6, 6.8, 7,
                  7.2, 7.4, 7.6, 7.8, 8, 8.2, 8.4, 8.6,
                  8.8, 9, 9.2, 9.4, 9.6, 9.8, 10,
                ],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  4, 4.2, 4.4, 4.6, 4.8, 5, 5.2, 5.4,
                  5.6, 5.8, 6, 6.2, 6.4, 6.6, 6.8, 7,
                  7.2, 7.4, 7.6, 7.8, 8, 8.2, 8.4, 8.6,
                  8.8, 9, 9.2, 9.4, 9.6, 9.8, 10,
                ],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.PORTAL,
                resolve: 4,
              },
              {
                case: StructureType.CANTILEVER,
                resolve: 6.6,
              },
              {
                case: StructureType.TTC,
                resolve: 6.6,
              },
            ],
          },
          alternative: true,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_a',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'length',
          label: 'Length',
          excelLabel: 'Length',
          inputType: INPUT_TYPE.DROPDOWN,
          activeCriteria: {
            pathToCheck: [PropertyName.STRUCTURE_BASIC, 'mast_a', 'steelwork'],
            allowedValues: [
              'DC380X100X54',
            ],
          },
          activeStatus: ACTIVE_STATUS.ACTIVE,
          possibleValues: [
            4.2, 4.6, 5, 5.4, 5.8,
            6.2, 6.6, 7, 7.4, 7.8,
            8.2, 8.6, 9, 9.4, 9.8,
            10.2,
          ],
          default: 6.6,
          alternative: true,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_a',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'foundation_type',
          label: 'Foundation Type',
          excelLabel: 'Foundation Type',
          activeCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            allowedValues: [StructureType.PORTAL],
          },
          activeStatus: ACTIVE_STATUS.ACTIVE,
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: Object.values(FoundationType),
          max: null,
          min: null,
          default: FoundationType.BOLTED,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_a',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'beta_angle',
          label: 'Rotation Angle',
          excelLabel: 'Rotation Angle',
          activeCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            allowedValues: [StructureType.CANTILEVER],
          },
          activeStatus: ACTIVE_STATUS.ACTIVE,
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 360,
          min: -360,
          default: 0,
          hintText:
              'Rotates the mast about its own axis. Use 90 for SSA',
          unit: 'deg',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_a',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
      ],
    },
    {
      name: 'mast_b',
      label: 'Mast B',
      excelLabel: 'Mast B',
      hintText: '',
      activeCriteria: {
        pathToCheck: [PropertyName.STRUCTURE_INFO, 'root', 'structure_type'],
        allowedValues: [StructureType.PORTAL],
      },
      activeStatus: ACTIVE_STATUS.ACTIVE,
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.STRUCTURE_BASIC,
      children: [
        {
          name: 'steelwork',
          label: 'Steelwork',
          excelLabel: 'Steelwork',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: ['DC300X90X41'],
          max: null,
          min: null,
          default: 'DC300X90X41',
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_b',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'foundation_level',
          label: 'Foundation Level',
          excelLabel: 'Foundation Level',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: null,
          min: null,
          default: 0,
          hintText: 'Measured from high rail to top of foundation level',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_b',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'length',
          label: 'Length',
          excelLabel: 'Length',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: [
            4, 4.2, 4.4, 4.6, 4.8, 5, 5.2, 5.4,
            5.6, 5.8, 6, 6.2, 6.4, 6.6, 6.8, 7,
            7.2, 7.4, 7.6, 7.8, 8, 8.2, 8.4, 8.6,
            8.8, 9, 9.2, 9.4, 9.6, 9.8, 10,
          ],
          max: 20,
          min: 1,
          default: 7,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_b',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'foundation_type',
          label: 'Foundation type',
          excelLabel: 'Foundation type',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: Object.values(FoundationType),
          max: null,
          min: null,
          default: FoundationType.BOLTED,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'mast_b',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
      ],
    },
    {
      name: 'boom',
      label: 'Boom',
      excelLabel: 'Boom',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.STRUCTURE_BASIC,
      activeCriteria: {
        pathToCheck: [PropertyName.STRUCTURE_INFO, 'root', 'structure_type'],
        allowedValues: [StructureType.PORTAL, StructureType.TTC],
      },
      activeStatus: ACTIVE_STATUS.ACTIVE,
      children: [
        {
          name: 'steelwork',
          label: 'Steelwork',
          excelLabel: 'Steelwork',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: [],
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.TTC,
                resolve: [
                  'Four Angle',
                ],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  'DC300X90X41',
                ],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: 'DC300X90X41',
              },
              {
                case: StructureType.PORTAL,
                resolve: 'DC300X90X41',
              },
              {
                case: StructureType.TTC,
                resolve: 'Four Angle',
              },
            ],
          },
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'boom',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'level',
          label: 'Level',
          excelLabel: 'Level',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 20,
          min: 0,
          default: 9.8,
          hintText:
              'Measured from high rail to centreline of boom',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'boom',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'length',
          label: 'Length',
          excelLabel: 'Length',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValuesCriteria: {
            pathToCheck: [PropertyName.STRUCTURE_BASIC, 'boom', 'steelwork'],
            possibleValuesPerCase: [
              {
                case: 'Four Angle',
                resolve: [
                  2.6, 3.4, 4.2, 5,
                  5.8, 6.6, 7.4, 8.2,
                  9, 9.8, 10.6,
                ],
              },
              {
                case: 'DC300X90X41',
                resolve: [
                  9, 9.2, 9.4, 9.6, 9.8, 10, 10.2, 10.4,
                  10.6, 10.8, 11, 11.2, 11.4, 11.6, 11.8, 12,
                  12.2, 12.4, 12.6, 12.8, 13, 13.2, 13.4, 13.6,
                  13.8, 14, 14.2, 14.4, 14.6, 14.8, 15, 15.2,
                  15.4, 15.6, 15.8, 16, 16.2, 16.4, 16.6, 16.8,
                  17, 17.2, 17.4, 17.6, 17.8, 18, 18.2, 18.4,
                  18.6, 18.8, 19, 19.2, 19.4, 19.6, 19.8, 20,
                  20.2, 20.4, 20.6, 20.8, 21,
                ],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [PropertyName.STRUCTURE_BASIC, 'boom', 'steelwork'],
            defaultValuePerCase: [
              {
                case: 'Four Angle',
                resolve: 3.4,
              },
              {
                case: 'DC300X90X41',
                resolve: 9,
              },
            ],
          },
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'boom',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'direction',
          label: 'Direction',
          excelLabel: 'Direction',
          activeCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            allowedValues: [StructureType.TTC],
          },
          activeStatus: ACTIVE_STATUS.ACTIVE,
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: ['Left', 'Right'],
          max: null,
          min: null,
          default: Direction.RIGHT,
          hintText: 'Rotates TTC to face left or right',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'boom',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
      ],
    },
    {
      name: 'wind_pressure',
      label: 'Wind Pressure',
      excelLabel: 'Wind Pressure',
      hintText: 'Calculated according to NR/L2/CIV/072',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.STRUCTURE_BASIC,
      children: [
        {
          name: 'qp_left',
          label: 'Qp(z) - Left',
          excelLabel: 'Qp(z) - Left',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: 0,
          default: 0.65,
          hintText: '',
          unit: 'kPa',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_pressure',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'qp_right',
          label: 'Qp(z) - Right',
          excelLabel: 'Qp(z) - Right',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: 0,
          default: 0.65,
          hintText: '',
          unit: 'kPa',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_pressure',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'qp_high',
          label: 'Qp(z) - High',
          excelLabel: 'Qp(z) - High',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: 0,
          default: 0.65,
          hintText: '',
          unit: 'kPa',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_pressure',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
        {
          name: 'qp_low',
          label: 'Qp(z) - Low',
          excelLabel: 'Qp(z) - Low',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: 0,
          default: 0.65,
          hintText: '',
          unit: 'kPa',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_pressure',
          sectionName: PropertyName.STRUCTURE_BASIC,
        },
      ],
    },
  ],
  wire_runs: [
    {
      name: 'root',
      displayType: DISPLAY_TYPE.ROOT,
      sectionName: PropertyName.WIRE_RUNS,
      children: [
        {
          name: 'wire_run_number',
          label: 'Wire Run Number',
          excelLabel: 'Wire Run Number',
          inputType: INPUT_TYPE.TEXT,
          possibleValues: [],
          max: null,
          min: null,
          default: 'WR',
          autoIncrement: true,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'equipment_type',
          label: 'Equipment Type',
          excelLabel: 'Equipment Type',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: Object.values(EquipmentType),
          max: null,
          min: null,
          default: EquipmentType.AT,
          hintText: 'AT: Auto Tension, FT: Fixed Termination',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'steel_support',
          label: 'Steel Support',
          excelLabel: 'Steel Support',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [SteelSupport.MASTA],
              },
              {
                case: StructureType.TTC,
                resolve: [SteelSupport.MASTA, SteelSupport.BOOM],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  SteelSupport.MASTA,
                  SteelSupport.BOOM,
                  SteelSupport.MASTB],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: SteelSupport.MASTA,
              },
              {
                case: StructureType.TTC,
                resolve: SteelSupport.BOOM,
              },
              {
                case: StructureType.PORTAL,
                resolve: SteelSupport.MASTB,
              },
            ],
          },
          max: null,
          min: null,
          default: SteelSupport.MASTA,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.WIRE_RUNS,
        },
      ],
    },
    {
      name: 'geometry',
      label: 'Geometry',
      excelLabel: 'Geometry',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.WIRE_RUNS,
      children: [
        {
          name: 'contact_height',
          label: 'Contact Height',
          excelLabel: 'Contact Height',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: 0,
          default: 4.7,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_height',
          label: 'Catenary Height',
          excelLabel: 'Catenary Height',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: 0,
          default: 6.0,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'stagger',
          label: 'Stagger',
          excelLabel: 'Stagger',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: -5,
          default: 0.23,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'reach',
          label: 'Reach',
          excelLabel: 'Reach',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          activeCriteria: {
            pathToCheck: [PropertyName.WIRE_RUNS, 'root', 'steel_support'],
            allowedValues: [SteelSupport.BOOM],
          },
          activeStatus: [],
          max: 5,
          min: -5,
          default: 1.8,
          hintText:
              'Positive when wire run is on the right side of support',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'recos',
          label: 'RECOS',
          excelLabel: 'RECOS',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: -50,
          default: 2.5,
          hintText:
              'Measured from Mast A for wire runs supported on Mast A or Boom. Measured from Mast B for wire runs on Mast B',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'track_level_difference',
          label: 'Track Level Difference',
          excelLabel: 'Track Level Difference',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: 0,
          default: 0,
          hintText:
              'A Positive value measured from this track to high rail level',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'drag_factor',
          label: 'Drag Factor (C)',
          excelLabel: 'Drag Factor (C)',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 3,
          min: 0,
          default: 1.2,
          hintText:
              'According to NR/L2/CIV/072 and 073. e.g. use 1.2 for CHS and 1.6 for SHS.',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.WIRE_RUNS,
        },
      ],
    },
    {
      name: 'equipment',
      label: 'Wire',
      excelLabel: 'Wire',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.WIRE_RUNS,
      children: [
        {
          name: 'weight_of_equipment',
          label: 'Weight',
          excelLabel: 'Weight',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 0.85,
          hintText:
              'Combined weight of wiring (Contact, Catenary, Droppers, etc.)',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'equipment',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'weight_of_ice_on_equipment',
          label: 'Weight Of Ice',
          excelLabel: 'Weight Of Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 0.3,
          hintText: 'Weight of ice on wires',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'equipment',
          sectionName: PropertyName.WIRE_RUNS,
        },
      ],
    },
    {
      name: 'registration',
      label: 'Registration',
      excelLabel: 'Registration',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.WIRE_RUNS,
      children: [
        {
          name: 'weight_of_registration',
          label: 'Weight',
          excelLabel: 'Weight',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 2,
          hintText:
              'Combined weight of SPS and registration in kN (excluding wires)',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'registration',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'area_of_registration',
          label: 'Area',
          excelLabel: 'Area',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.85,
          hintText:
              'Combined along track area of SPS and registration in m^2',
          unit: 'm^2',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'registration',
          sectionName: PropertyName.WIRE_RUNS,
        },
      ],
    },
    {
      name: 'radial_loads',
      label: 'Radial Loads',
      excelLabel: 'Radial Loads',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.WIRE_RUNS,
      children: [
        {
          name: 'contact_at_18',
          label: 'Contact (-18C)',
          excelLabel: 'Contact (-18C)',
          inputType: INPUT_TYPE.NUMBER,
          // TODO: Make things right about contact activity as erfan told
          //  activeCriteria: {
          //   pathToCheck: [PropertyName.WIRE_RUNS, 'equipment_type'],
          //    valueToCheck: [EquipmentType.FT],
          // },
          max: 10,
          min: -10,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_at_18',
          label: 'Catenary (-18C)',
          excelLabel: 'Catenary (-18C)',
          inputType: INPUT_TYPE.NUMBER,
          //  activeCriteria: {
          //   pathToCheck: [PropertyName.WIRE_RUNS, 'equipment_type'],
          //   valueToCheck: [EquipmentType.FT],
          //   },
          max: 10,
          min: -10,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'contact_at_5',
          label: 'Contact (-5C)',
          excelLabel: 'Contact (-5C)',
          inputType: INPUT_TYPE.NUMBER,
          // activeCriteria: {
          //  pathToCheck: [PropertyName.WIRE_RUNS, 'equipment_type'],
          //   valueToCheck: [EquipmentType.FT],
          //  },
          max: 10,
          min: -10,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_at_5',
          label: 'Catenary (-5C)',
          excelLabel: 'Catenary (-5C)',
          inputType: INPUT_TYPE.NUMBER,
          //  activeCriteria: {
          //   pathToCheck: [PropertyName.WIRE_RUNS, 'equipment_type'],
          //  valueToCheck: [EquipmentType.FT],
          //  },
          max: 10,
          min: -10,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'contact_at_10',
          label: 'Contact (10C)',
          excelLabel: 'Contact (10C)',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: -10,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_at_10',
          label: 'Catenary (10C)',
          excelLabel: 'Catenary (10C)',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: -10,
          default: 0.3,
          hintText: 'kN',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
      ],
    },
    {
      name: 'wind_loads',
      label: 'Wind Loads',
      excelLabel: 'Wind Loads',
      hintText: 'Calculated according to NR/L2/CIV/072',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.WIRE_RUNS,
      children: [
        {
          name: 'contact_from_left',
          label: 'Contact Left',
          excelLabel: 'Contact Left',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'contact_from_right',
          label: 'Contact Right',
          excelLabel: 'Contact Right',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_from_left',
          label: 'Catenary Left',
          excelLabel: 'Catenary Left',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_from_right',
          label: 'Catenary Right',
          excelLabel: 'Catenary Right',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'contact_from_left_with_ice',
          label: 'Contact Left With Ice',
          excelLabel: 'Contact Left With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'contact_from_right_with_ice',
          label: 'Contact Right With Ice',
          excelLabel: 'Contact Right With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_from_left_with_ice',
          label: 'Catenary Left With Ice',
          excelLabel: 'Catenary Left With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.7,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
        {
          name: 'catenary_from_right_with_ice',
          label: 'Catenary Right With Ice',
          excelLabel: 'Catenary Right With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.7,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.WIRE_RUNS,
        },
      ],
    },
  ],
  ancillary_wires: [
    {
      name: 'root',
      displayType: DISPLAY_TYPE.ROOT,
      sectionName: PropertyName.ANCILLARY_WIRES,
      children: [
        {
          name: 'wire_name',
          label: 'Wire Name',
          excelLabel: 'Wire Name',
          inputType: INPUT_TYPE.TEXT,
          possibleValues: [],
          max: null,
          min: null,
          default: 'EW',
          autoIncrement: true,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'steel_support',
          label: 'Steel Support',
          excelLabel: 'Steel Support',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [SteelSupport.MASTA],
              },
              {
                case: StructureType.TTC,
                resolve: [SteelSupport.MASTA, SteelSupport.BOOM],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  SteelSupport.MASTA,
                  SteelSupport.BOOM,
                  SteelSupport.MASTB],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: SteelSupport.MASTA,
              },
              {
                case: StructureType.TTC,
                resolve: SteelSupport.BOOM,
              },
              {
                case: StructureType.PORTAL,
                resolve: SteelSupport.MASTB,
              },
            ],
          },
          default: SteelSupport.MASTA,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
      ],
    },
    {
      name: 'geometry',
      label: 'Geometry',
      excelLabel: 'Geometry',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCILLARY_WIRES,
      children: [
        {
          name: 'wire_height',
          label: 'Height',
          excelLabel: 'Height',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 5,
          hintText: 'Measured from high rail level',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'offset_from_mast_centre',
          label: 'Offset From Mast Centre',
          excelLabel: 'Offset From Mast Centre',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: -50,
          default: 0.7,
          hintText:
              'Measured from Mast A for wires supported on Mast A or Boom. Measured from Mast B for wires on Mast B',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'reach',
          label: 'Reach',
          excelLabel: 'Reach',
          inputType: INPUT_TYPE.NUMBER,
          activeCriteria: {
            pathToCheck: [
              PropertyName.ANCILLARY_WIRES,
              'root',
              'steel_support'],
            allowedValues: [SteelSupport.BOOM],
          },
          activeStatus: [],
          max: 5,
          min: -5,
          default: 0.7,
          hintText:
              'Positive when wire is on the right side of support',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'drag_factor',
          label: 'Drag Factor (C)',
          excelLabel: 'Drag Factor (C)',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 1.2,
          hintText:
              'According to NR/L2/CIV/072 and 073. e.g.use 1.2 for CHS and 1.6 for SHS.',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
      ],
    },
    {
      name: 'registration',
      label: 'Registration',
      excelLabel: 'Registration',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCILLARY_WIRES,
      children: [
        {
          name: 'weight_of_support',
          label: 'Weight',
          excelLabel: 'Weight',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 1.4,
          hintText: 'Weight of SPS and registration excluding wire',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'registration',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'area_of_support',
          label: 'Area',
          excelLabel: 'Area',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: 'Area of SPS and registration exposed to wind',
          unit: 'm^2',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'registration',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
      ],
    },
    {
      name: 'equipment',
      label: 'Wire',
      excelLabel: 'Wire',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCILLARY_WIRES,
      children: [
        {
          name: 'weight_of_equipment',
          label: 'Weight',
          excelLabel: 'Weight',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: null,
          min: 0,
          default: 0.7,
          hintText: 'Weight of wires',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'equipment',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'weight_of_ice_on_equipment',
          label: 'Weight Of Ice',
          excelLabel: 'Weight Of Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.4,
          hintText: 'Weight of ice on wire',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'equipment',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
      ],
    },
    {
      name: 'radial_loads',
      label: 'Radial Loads',
      excelLabel: 'Radial Loads',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCILLARY_WIRES,
      children: [
        {
          name: 'radial_load_at_18',
          label: '-18C',
          excelLabel: 'at -18C',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'radial_load_at_5',
          label: '-5C',
          excelLabel: 'at -5C',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.2,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'radial_load_at_10',
          label: '10C',
          excelLabel: 'at 10C',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.1,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'radial_loads',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
      ],
    },
    {
      name: 'wind_loads',
      label: 'Wind Loads',
      excelLabel: 'Wind Loads',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCILLARY_WIRES,
      children: [
        {
          name: 'wind_load_from_left',
          label: 'Left',
          excelLabel: 'From Left',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.4,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'wind_load_from_right',
          label: 'Right',
          excelLabel: 'From Right',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.4,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'wind_load_from_left_with_ice',
          label: 'Left With Ice',
          excelLabel: 'From Left With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.6,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
        {
          name: 'wind_load_from_right_with_ice',
          label: 'Right With Ice',
          excelLabel: 'From Right With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.6,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCILLARY_WIRES,
        },
      ],
    },
  ],
  anchors: [
    {
      name: 'root',
      displayType: DISPLAY_TYPE.ROOT,
      sectionName: PropertyName.ANCHORS,
      children: [
        {
          name: 'anchor_name',
          label: 'Anchor Name',
          excelLabel: 'Anchor Name',
          inputType: INPUT_TYPE.TEXT,
          possibleValues: [],
          max: null,
          min: null,
          default: 'ANC',
          autoIncrement: true,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'steel_support',
          label: 'Steel Support',
          excelLabel: 'Steel Support',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [SteelSupport.MASTA],
              },
              {
                case: StructureType.TTC,
                resolve: [SteelSupport.MASTA, SteelSupport.BOOM],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  SteelSupport.MASTA,
                  SteelSupport.BOOM,
                  SteelSupport.MASTB],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: SteelSupport.MASTA,
              },
              {
                case: StructureType.TTC,
                resolve: SteelSupport.BOOM,
              },
              {
                case: StructureType.PORTAL,
                resolve: SteelSupport.MASTB,
              },
            ],
          },
          default: SteelSupport.MASTA,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.ANCHORS,
        },
      ],
    },
    {
      name: 'geometry',
      label: 'Geometry',
      excelLabel: 'Geometry',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCHORS,
      children: [
        {
          name: 'anchor_height',
          label: 'Height',
          excelLabel: 'Anchor Height',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 20,
          min: 0,
          default: 5.0,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'direction',
          label: 'Direction',
          excelLabel: 'Direction',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: ['High Chainage', 'Low Chainage'],
          max: null,
          min: null,
          default: Direction.HIGH_CHAINAGE,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'offset_from_mast_centre',
          label: 'Offset From Mast Centre',
          excelLabel: 'Offset From Mast Centre',
          inputType: INPUT_TYPE.NUMBER,
          activeCriteria: {
            pathToCheck: [PropertyName.ANCHORS, 'root', 'steel_support'],
            allowedValues: [SteelSupport.BOOM],
          },
          activeStatus: [],
          max: 50,
          min: -50,
          default: 0,
          hintText: 'Measured from centreline of Mast A',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'track_level_difference',
          label: 'Track Level Difference',
          excelLabel: 'Track Level Difference',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0,
          hintText: 'A Positive value measured from this track to high rail level',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'angle',
          label: 'Angle',
          excelLabel: 'Angle',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 15,
          min: -15,
          default: 0,
          hintText: '0 if anchor is parallel to track, otherwise looking towards direction of anchor, clockwise degree positive, anti-clockwise degree negative',
          unit: 'deg',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'drag_factor',
          label: 'Drag Factor (C)',
          excelLabel: 'Drag Factor (C)',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 1.2,
          hintText: 'According to NR/L2/CIV/072 and 073. Use 1.8 for conservative results',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'geometry',
          sectionName: PropertyName.ANCHORS,
        },
      ],
    },
    {
      name: 'registration',
      label: 'Registration',
      excelLabel: 'Registration',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCHORS,
      children: [
        {
          name: 'weight_of_support',
          label: 'Weight',
          excelLabel: 'Weight',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: null,
          min: 0,
          default: 1,
          hintText: 'Weight of SPS and registration excluding wire',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'registration',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'area_of_support',
          label: 'Area',
          excelLabel: 'Area',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0.,
          default: 0.4,
          hintText: 'Area of SPS and registration exposed to wind',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'registration',
          sectionName: PropertyName.ANCHORS,
        },
      ],
    },
    {
      name: 'equipment',
      label: 'Equipment',
      excelLabel: 'Equipment',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCHORS,
      children: [
        {
          name: 'weight_of_equipment',
          label: 'Weight',
          excelLabel: 'Weight',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.35,
          hintText: 'Weight of wire',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'equipment',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'weight_of_ice_on_equipment',
          label: 'Weight Of Ice',
          excelLabel: 'Weight Of Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.2,
          hintText: 'Weight of ice on wires',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'equipment',
          sectionName: PropertyName.ANCHORS,
        },
      ],
    },
    {
      name: 'tension',
      label: 'Tension',
      excelLabel: 'Tension',
      hintText: '',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCHORS,
      children: [
        {
          name: 'equipment_type',
          label: 'Type',
          excelLabel: 'Equipment Type',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: Object.values(EquipmentType),
          max: null,
          min: null,
          default: EquipmentType.AT,
          hintText: 'AT: Auto Tension, FT: Fixed Termination',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'tension',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'tension_at_18',
          label: '-18C',
          excelLabel: 'at -18C',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 11,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'tension',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'tension_at_5',
          label: '-5',
          excelLabel: 'at -5',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 11,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'tension',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'tension_at_10',
          label: '10C',
          excelLabel: 'at 10C',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 11,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'tension',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'accidental_load_case',
          label: 'Accidental Load',
          excelLabel: 'Accidental Load',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: ['No', 'Yes'],
          default: 'No',
          hintText:
              'Accidental load applies when broken wire has a destabilising effect on structure e.g. SSA with back to back anchors. Refer to NR/L2/CIV/073',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'tension',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'accidental_tension',
          label: 'Accidental Tension',
          excelLabel: 'Accidental Tension',
          inputType: INPUT_TYPE.NUMBER,
          activeCriteria: {
            pathToCheck: [
              PropertyName.ANCHORS,
              'tension',
              'accidental_load_case'],
            allowedValues: [true],
          },
          activeStatus: [],
          max: 50,
          min: 0,
          default: 11.0,
          hintText:
              'Broken wire tension. Use tension at -5C. Refer to NR/L2/CIV/073',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'tension',
          sectionName: PropertyName.ANCHORS,
        },
      ],
    },
    {
      name: 'wind_loads',
      label: 'Wind Loads',
      excelLabel: 'Wind Loads',
      hintText: 'Wind load on wiring, calculated as per NR/L2/CIV/072',
      displayType: DISPLAY_TYPE.GROUP,
      sectionName: PropertyName.ANCHORS,
      children: [
        {
          name: 'wind_load_from_left',
          label: 'Left',
          excelLabel: 'From Left',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.2,
          hintText: 'Wind load on wire',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'wind_load_from_right',
          label: 'Right',
          excelLabel: 'From Right',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.2,
          hintText: 'Wind load on wire',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'wind_load_from_left_with_ice',
          label: 'Left With Ice',
          excelLabel: 'From Left With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: 'Wind load on wire with ice',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCHORS,
        },
        {
          name: 'wind_load_from_right_with_ice',
          label: 'Right With Ice',
          excelLabel: 'From Right With Ice',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.3,
          hintText: 'Wind load on wire with ice',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'wind_loads',
          sectionName: PropertyName.ANCHORS,
        },
      ],
    },
  ],
  ties: [
    {
      name: 'root',
      displayType: DISPLAY_TYPE.ROOT,
      sectionName: PropertyName.TIES,
      children: [
        {
          name: 'steel_support',
          label: 'Steel Support',
          excelLabel: 'Steel Support',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [SteelSupport.MASTA],
              },
              {
                case: StructureType.TTC,
                resolve: [SteelSupport.MASTA],
              },
              {
                case: StructureType.PORTAL,
                resolve: [SteelSupport.MASTA, SteelSupport.MASTB],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: SteelSupport.MASTA,
              },
              {
                case: StructureType.TTC,
                resolve: SteelSupport.MASTA,
              },
              {
                case: StructureType.PORTAL,
                resolve: SteelSupport.MASTB,
              },
            ],
          },
          default: SteelSupport.MASTA,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.TIES,
        },
        {
          name: 'type',
          label: 'Type',
          excelLabel: 'Type',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: ['25mm Diameter'],
          max: null,
          min: null,
          default: '25mm Diameter',
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.TIES,
        },
        {
          name: 'tie_height',
          label: 'Tie Height',
          excelLabel: 'Tie Height',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 20,
          min: 0,
          default: 5.3,
          hintText: 'Measured from high rail level',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.TIES,
        },
        {
          name: 'tie_spacing',
          label: 'Tie Spacing',
          excelLabel: 'Tie Spacing',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: -10,
          default: 4.5,
          hintText: 'Positive value for tie on high mileage',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.TIES,
        },
        {
          name: 'foundation_level',
          label: 'Foundation Level',
          excelLabel: 'Foundation Level',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 10,
          min: -10,
          default: 0,
          hintText: 'Measured from high rail to top of foundation',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.TIES,
        },
      ],
    },
  ],
  switches: [
    {
      name: 'root',
      displayType: DISPLAY_TYPE.ROOT,
      sectionName: PropertyName.SWITCHES,
      children: [
        {
          name: 'steel_support',
          label: 'Steel Support',
          excelLabel: 'Steel Support',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [SteelSupport.MASTA],
              },
              {
                case: StructureType.TTC,
                resolve: [SteelSupport.MASTA, SteelSupport.BOOM],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  SteelSupport.MASTA,
                  SteelSupport.BOOM,
                  SteelSupport.MASTB],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: SteelSupport.MASTA,
              },
              {
                case: StructureType.TTC,
                resolve: SteelSupport.BOOM,
              },
              {
                case: StructureType.PORTAL,
                resolve: SteelSupport.MASTB,
              },
            ],
          },
          default: SteelSupport.MASTA,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.SWITCHES,
        },
        {
          name: 'height',
          label: 'Height',
          excelLabel: 'Height',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 7.0,
          hintText: 'Measured from high rail level',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.SWITCHES,
        },
        {
          name: 'offset_from_mast_a',
          label: 'Offset From Mast A',
          excelLabel: 'Offset From Mast A',
          inputType: INPUT_TYPE.NUMBER,
          activeCriteria: {
            pathToCheck: [PropertyName.SWITCHES, 'root', 'steel_support'],
            allowedValues: [SteelSupport.BOOM],
          },
          activeStatus: [],
          max: 50,
          min: -50,
          default: 5.0,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.SWITCHES,
        },
        {
          name: 'direction',
          label: 'Direction (Mast Switches)',
          excelLabel: 'Direction (Mast Switches)',
          inputType: INPUT_TYPE.DROPDOWN,
          activeCriteria: {
            pathToCheck: [PropertyName.SWITCHES, 'root', 'steel_support'],
            allowedValues: [SteelSupport.MASTA, SteelSupport.MASTB],
          },
          activeStatus: [],
          possibleValues: ['Left', 'Right', 'High', 'Low'],
          max: null,
          min: null,
          default: 'Left',
          hintText: 'Relative position of switch on supporting mast',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.SWITCHES,
        },
        {
          name: 'weight',
          label: 'Weight',
          excelLabel: 'Weight',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 50,
          min: 0,
          default: 2,
          hintText: '',
          unit: 'kN',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.SWITCHES,
        },
        {
          name: 'along_track_area',
          label: 'Along Track Area',
          excelLabel: 'Along Track Area',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.4,
          hintText: '',
          unit: 'm^2',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.SWITCHES,
        },
        {
          name: 'across_track_area',
          label: 'Across Track Area',
          excelLabel: 'Across Track Area',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 5,
          min: 0,
          default: 0.4,
          hintText: '',
          unit: 'm^2',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.SWITCHES,
        },
      ],
    },
  ],
  construction_loads: [
    {
      name: 'root',
      displayType: DISPLAY_TYPE.ROOT,
      sectionName: PropertyName.CONSTRUCTION_LOADS,
      children: [
        {
          name: 'steel_support',
          label: 'Steel Support',
          excelLabel: 'Steel Support',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValuesCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            possibleValuesPerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: [SteelSupport.MASTA],
              },
              {
                case: StructureType.TTC,
                resolve: [SteelSupport.MASTA, SteelSupport.BOOM],
              },
              {
                case: StructureType.PORTAL,
                resolve: [
                  SteelSupport.MASTA,
                  SteelSupport.BOOM,
                  SteelSupport.MASTB],
              },
            ],
          },
          defaultCriteria: {
            pathToCheck: [
              PropertyName.STRUCTURE_INFO,
              'root',
              'structure_type'],
            defaultValuePerCase: [
              {
                case: StructureType.CANTILEVER,
                resolve: SteelSupport.MASTA,
              },
              {
                case: StructureType.TTC,
                resolve: SteelSupport.BOOM,
              },
              {
                case: StructureType.PORTAL,
                resolve: SteelSupport.MASTB,
              },
            ],
          },
          default: SteelSupport.MASTA,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.CONSTRUCTION_LOADS,
        },
        {
          name: 'height',
          label: 'Height',
          excelLabel: 'Height',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 20,
          min: 0,
          default: 5,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.CONSTRUCTION_LOADS,
        },
        {
          name: 'offset_from_mast_a',
          label: 'Offset From Mast A',
          excelLabel: 'Offset From Mast A',
          inputType: INPUT_TYPE.NUMBER,
          activeCriteria: {
            pathToCheck: [
              PropertyName.CONSTRUCTION_LOADS,
              'root',
              'steel_support'],
            allowedValues: [SteelSupport.BOOM],
          },
          activeStatus: [],
          max: 50,
          min: -50,
          default: 5,
          hintText: '',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.CONSTRUCTION_LOADS,
        },
        {
          name: 'direction_relative_to_mast',
          label: 'Direction Relative To Mast',
          excelLabel: 'Direction Relative To Mast',
          inputType: INPUT_TYPE.DROPDOWN,
          possibleValues: ['Left', 'Right', 'High', 'Low'],
          activeCriteria: {
            pathToCheck: [PropertyName.SWITCHES, 'root', 'steel_support'],
            allowedValues: [SteelSupport.MASTA, SteelSupport.MASTB],
          },
          activeStatus: [],
          default: 'Left',
          hintText: 'Relative position of construction load to supporting mast',
          unit: 'm',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.CONSTRUCTION_LOADS,
        },
        {
          name: 'construction_load',
          label: 'Construction Load',
          excelLabel: 'Construction Load',
          inputType: INPUT_TYPE.NUMBER,
          possibleValues: [],
          max: 20,
          min: 0,
          default: 1,
          hintText: '',
          unit: '',
          displayType: DISPLAY_TYPE.INPUT,
          groupName: 'root',
          sectionName: PropertyName.CONSTRUCTION_LOADS,
        },
      ],
    },
  ],
};
